version: '3.9'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - backend
    - frontend
  backend:
    container_name: backend
    hostname: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    restart: unless-stopped

    depends_on:
     - mongodb
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env

  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
