version: '3.9'
services:
#  dev:
#    container_name: server-dev-backend
#    image: server-dev:1.0.0
#    build:
#      context: ./backend
#      dockerfile: ./backend/Dockerfile
#    command: npm run start:debug
#    ports:
#      - 3333:3000
#      - 9229:9229
#    networks:
#      - server-network
#    volumes:
#      - .:/home/szymon/Desktop/Inzynierka/file-server
#      - /home/szymon/Desktop/Inzynierka/file-server/node_modules
#    restart: unless-stopped
#    depends_on:
#      - mongodb

  mongodb:
    image: mongo:5.0.0
    container_name: server-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - server-network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  server-network: